# record all kinds of type
# pm type
LINKEDIN_TYPE = 1
PM_LANG_ITEM_TYPE = 0
PM_CITY_ITEM_TYPE = 1
PM_SERVICE_ITEM_TYPE = 2
REALTOR_MESSAGE_TYPE = 3

#quiz type
PM_QUIZ_TYPE = 0

#pm inspection report note type
PM_INSPECTION_REPORT_TYPE = 3
PM_EXPENSE_TYPE = 4

#user progress bar
USER_PROGRESS_BAR_TYPE = 0
HOME_PROGRESS_BAR_TYPE = 1

#pm bill incomes type
PM_INCOME_TYPE = 0

#picture type
PIC_AVATAR_TYPE = 0
PIC_URL_TYPE = 1

#file type
FILE_S3_TYPE = 0

#status log type
STATUS_LOG_USER_TYPE = 0

#extra file type
EXTRA_USER_INSPECTION_REPORT_TYPE = 0
EXTRA_USER_CONTRACT_TYEP = 1

#submit type
EXPENSE_SUBMIT_TYPE = 0

# census report type
CENSUS_REPORT_TYPE_STATE = 0
CENSUS_REPORT_TYPE_MSA = 1
CENSUS_REPORT_TYPE_COUNTY = 2
CENSUS_REPORT_TYPE_CITY = 3
CENSUS_REPORT_TYPE_TOWN = 4
CENSUS_REPORT_TYPE_NEIGHBORHOOD = 5
CENSUS_REPORT_TYPE_ZIPCODE = 6
